### ISSUE TITLE
Errors when using non-ascii identifiers in Fennel

### ISSUE THREAD

**Issue by alexaandru** [TravonteD/tree-sitter-fennel#30]
### To reproduce:

1. given `f.fnl` with content `(local ⧔ 42)`
2. highlighting is broken
3. using playground, it reports:

```
ERROR [0, 0] - [0, 14]
      ERROR [0, 7] - [0, 13]
```

Fennel itself can compile the above just fine:

```
$ fennel --compile f.fnl 
local _e2_a7_94 = 42
return nil
```

so it is valid code.

**Comment by TravonteD** [comment]
Thanks for the report, I'll work up a patch to get it fixed

**Comment by alexaandru** [comment]
Many thanks for your work! Cheers! :)

**Comment by TravonteD** [comment]
I just merged a pretty large re-write, with a fresh install check if you still are getting the parser error

**Comment by alexaandru** [comment]
I don't know how to test this directly, I was only using it indirectly, via https://github.com/nvim-treesitter/nvim-treesitter plugin. Could you please tell me how can I compile it? Keeps complaining it cannot find <tree_sitter/parser.h>.

I did download tree-sitter itself, and updated `INCS` to add `-I../tree-sitter/lib/include` but it still won't compile.

Thank you!

**Comment by otommod** [comment]
The new parser is now used by nvim-treesitter.  You can update the plugin and then `:TSUpdate` and test.

**Comment by alexaandru** [comment]
It works, errors are all gone now! :) 

Thank you! :)
